version: '3'

services:

  openhim-dev:
    container_name: openhim-dev
    image: node:8
    volumes:
      - "../openhim-core/openhim-core-js:/openhim-core-js"
    command: node /openhim-core-js/bin/openhim-core.js
    depends_on:
     - mongo
    ports:
      - "8080:8080"
    environment:
      mongo_url: mongodb://mongo/openhim
      mongo_atnaUrl: "mongodb://mongo/openhim"


  mongo:
    image: mongo:3
    ports:
      - "27017:27017"


  openhim-console:
    image: abiosoft/caddy
    # mount a locally built version (app/) not the prebuilt release
    # but either will work as long as volume is pointing to the app
    volumes:
      - "../openhim-console/openhim-console/app:/srv"
      - "../openhim-console/Caddyfile:/etc/Caddyfile"
    links:
      - openhim-dev
    ports:
      - "8081:8081"
