version: '3'

services:

  openhim-docker:
    container_name: openhim-core
    image: jembi/openhim-core
    depends_on:
     - mongo
    ports:
      - "8080:8080"
    environment:
      mongo_url: mongodb://mongo/openhim
      mongo_atnaUrl: "mongodb://mongo/openhim"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  openhim-console:
    image: abiosoft/caddy
    # path to the prebuilt release
    volumes:
      - "../openhim-console-prebuilt:/srv"
      - "./Caddyfile:/etc/Caddyfile"
      - "$HOME/.caddy:/root/.caddy"
    links:
      - openhim-docker
    ports:
      - "8081:8081"
